### PR TITLE
remove quagga's default multipath relax behavior which'd cause

### PR DESCRIPTION
**Pull request by lguohan**
weird routing problems.

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]
ok

**Comment by pavel-shirshov** [comment]
The commit which brought this functionality
https://github.com/opensourcerouting/quagga/commit/0b597ef00ec7c7eebd836e2b1d5a266efcd60005

**Comment by lguohan** [comment]
I am using this patch. https://github.com/FRRouting/frr/commit/16fc1eec45d247656a86329c1d27aafb535619ae

but I simplified the patch changes the aspath multipath relax behavior.

**Comment by heidinet** [comment]
Can you elaborate on "weird routing problems"?  It seems that with current diff, a sonic box will no longer aggregate attributes from multiple paths (behave as "no-as-set" option is configured in FRR).

**Pull request merged**
